### ISSUE TITLE
cannot submit boost job

### ISSUE THREAD

**Issue by pyramids33** [MatterPool/boostpow-js#3]
const job = boost.BoostPowJob.fromRawTransaction(txhex);
    console.log(job);
    console.log(job.getTxid());

    const boostRequestSubmit = await boost.Graph().submitBoostJob(txhex);

    {
        success: false,
        code: -1,
        message: "Cannot read property 'getTxid' of undefined",
        error: ''
    }

**Comment by pyramids33** [comment]
here is output from the first few lines

```
BoostPowJobModel {
  content: <Buffer 83 43 eb 74 77 1d 28 69 38 35 53 29 20 d8 36 39 52 52 8a 12 00 00 00 00 00 00 00 00 00 00 00 00>,
  difficulty: 1,
  category: <Buffer 01 00 00 00>,
  tag: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  additionalData: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  userNonce: <Buffer d8 41 b0 99>,
  txid: '75ebb9c8cdd2aa8fac691b6f977eff88c1effc568b11971689915fff71d7b229',
  vout: 2,
  value: 1800
}
75ebb9c8cdd2aa8fac691b6f977eff88c1effc568b11971689915fff71d7b229
```

**Comment by attilaaf** [comment]
The method  `xxxx` is available to detect boost outputs.

I see you fixed the boostpow-api server, thank you! re: https://github.com/MatterPool/boostpow-api/pull/13

I'll merge and deploy production server within the hour.
